CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    role ENUM('accountant', 'business_owner', 'admin') NOT NULL,
    is_active BOOLEAN,
    email_verified BOOLEAN,
    email_verified_at TIMESTAMP NULL,
    last_login_at TIMESTAMP NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE password_reset_tokens (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    token VARCHAR(255) UNIQUE NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP NULL,
    created_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE companies (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    registration_number VARCHAR(100) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    address TEXT,
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    country VARCHAR(100),
    email VARCHAR(255),
    phone VARCHAR(50),
    website VARCHAR(255),
    tax_id VARCHAR(100),
    vat_number VARCHAR(100),
    fiscal_year_start DATE,
    currency VARCHAR(3),
    is_active BOOLEAN,
    created_by_user_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (created_by_user_id) REFERENCES users(id)
);

CREATE TABLE user_company_access (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    access_level ENUM('full_access', 'view_only', 'limited') NOT NULL,
    status ENUM('active', 'pending', 'revoked', 'expired') NOT NULL,
    granted_at TIMESTAMP NULL,
    granted_by_user_id BIGINT,
    revoked_at TIMESTAMP NULL,
    revoked_by_user_id BIGINT,
    expires_at TIMESTAMP NULL,
    notes TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (granted_by_user_id) REFERENCES users(id),
    FOREIGN KEY (revoked_by_user_id) REFERENCES users(id)
);

CREATE TABLE bank_accounts (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    bank_name VARCHAR(255) NOT NULL,
    account_name VARCHAR(255),
    account_number_masked VARCHAR(50),
    account_type ENUM('checking', 'savings', 'credit_card', 'line_of_credit') NOT NULL,
    currency VARCHAR(3),
    is_active BOOLEAN,
    last_sync_at TIMESTAMP NULL,
    balance DECIMAL(15, 2),
    created_by_user_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (created_by_user_id) REFERENCES users(id)
);

CREATE TABLE invoices (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    invoice_number VARCHAR(100) NOT NULL,
    vendor_name VARCHAR(255),
    vendor_tax_id VARCHAR(100),
    invoice_date DATE,
    due_date DATE,
    payment_date DATE NULL,
    subtotal DECIMAL(15, 2),
    vat_rate DECIMAL(5, 2),
    vat_amount DECIMAL(15, 2),
    total_amount DECIMAL(15, 2) NOT NULL,
    currency VARCHAR(3),
    original_file_name VARCHAR(255),
    file_path VARCHAR(500),
    file_type VARCHAR(50),
    file_size_kb INT,
    status ENUM('uploaded', 'processing', 'processed', 'verified', 'matched', 'partially_matched', 'exported', 'error') NOT NULL,
    ai_confidence_score DECIMAL(5, 4),
    ai_extraction_complete BOOLEAN,
    ai_processed_at TIMESTAMP NULL,
    verified BOOLEAN,
    verified_by_user_id BIGINT,
    verified_at TIMESTAMP NULL,
    is_matched BOOLEAN,
    matched_amount DECIMAL(15, 2),
    number_of_payments INT,
    last_four_digits_card VARCHAR(4),
    notes TEXT,
    internal_reference VARCHAR(100),
    uploaded_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (verified_by_user_id) REFERENCES users(id),
    FOREIGN KEY (uploaded_by_user_id) REFERENCES users(id)
);

CREATE TABLE invoice_line_items (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    invoice_id BIGINT NOT NULL,
    line_number INT NOT NULL,
    description TEXT,
    category VARCHAR(100),
    quantity DECIMAL(10, 2),
    unit_price DECIMAL(15, 2),
    vat_rate DECIMAL(5, 2),
    total_amount DECIMAL(15, 2) NOT NULL,
    ai_confidence_score DECIMAL(5, 4),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (invoice_id) REFERENCES invoices(id)
);

CREATE TABLE transactions (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    bank_account_id BIGINT NOT NULL,
    transaction_date DATE NOT NULL,
    value_date DATE,
    description TEXT NOT NULL,
    reference_number VARCHAR(100),
    amount DECIMAL(15, 2) NOT NULL,
    currency VARCHAR(3),
    transaction_type ENUM('debit', 'credit', 'fee', 'interest', 'transfer') NOT NULL,
    direction ENUM('in', 'out') NOT NULL,
    category VARCHAR(100),
    subcategory VARCHAR(100),
    status ENUM('unmatched', 'matched', 'partially_matched', 'review_needed', 'ignored') NOT NULL,
    is_matched BOOLEAN,
    matched_amount DECIMAL(15, 2),
    ai_suggested_category VARCHAR(100),
    ai_confidence_score DECIMAL(5, 4),
    is_reconciled BOOLEAN,
    reconciled_at TIMESTAMP NULL,
    reconciled_by_user_id BIGINT,
    is_duplicate BOOLEAN,
    duplicate_of_transaction_id BIGINT,
    imported_from VARCHAR(100),
    import_batch_id VARCHAR(100),
    imported_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (bank_account_id) REFERENCES bank_accounts(id),
    FOREIGN KEY (reconciled_by_user_id) REFERENCES users(id),
    FOREIGN KEY (imported_by_user_id) REFERENCES users(id),
    FOREIGN KEY (duplicate_of_transaction_id) REFERENCES transactions(id)
);

CREATE TABLE invoice_transaction_matches (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    invoice_id BIGINT NOT NULL,
    transaction_id BIGINT NOT NULL,
    match_type ENUM('full', 'partial', 'split_invoice', 'split_transaction') NOT NULL,
    matched_amount DECIMAL(15, 2) NOT NULL,
    matched_by ENUM('ai_automatic', 'ai_suggested', 'manual', 'rule_based') NOT NULL,
    match_confidence DECIMAL(5, 4),
    match_reason TEXT,
    status ENUM('active', 'disputed', 'cancelled', 'confirmed') NOT NULL,
    matched_by_user_id BIGINT,
    confirmed_by_user_id BIGINT,
    confirmed_at TIMESTAMP NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (invoice_id) REFERENCES invoices(id),
    FOREIGN KEY (transaction_id) REFERENCES transactions(id),
    FOREIGN KEY (matched_by_user_id) REFERENCES users(id),
    FOREIGN KEY (confirmed_by_user_id) REFERENCES users(id)
);

CREATE TABLE anomalies (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    anomaly_type ENUM('duplicate_transaction', 'duplicate_invoice', 'amount_mismatch', 'missing_invoice', 'missing_transaction', 'date_discrepancy', 'unusual_amount', 'vat_calculation_error', 'vendor_mismatch', 'unmatched_for_long_time', 'other') NOT NULL,
    severity ENUM('critical', 'high', 'medium', 'low', 'info') NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    suggested_action TEXT,
    invoice_id BIGINT,
    transaction_id BIGINT,
    related_invoice_id BIGINT,
    related_transaction_id BIGINT,
    status ENUM('open', 'investigating', 'resolved', 'ignored', 'false_positive') NOT NULL,
    resolved_by_user_id BIGINT,
    resolved_at TIMESTAMP NULL,
    resolution_notes TEXT,
    detected_by ENUM('ai', 'rule_engine', 'manual', 'system') NOT NULL,
    detection_confidence DECIMAL(5, 4),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (invoice_id) REFERENCES invoices(id),
    FOREIGN KEY (transaction_id) REFERENCES transactions(id),
    FOREIGN KEY (related_invoice_id) REFERENCES invoices(id),
    FOREIGN KEY (related_transaction_id) REFERENCES transactions(id),
    FOREIGN KEY (resolved_by_user_id) REFERENCES users(id)
);

CREATE TABLE exports (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    export_type ENUM('vat_report', 'consolidated_transactions', 'invoice_list', 'transaction_list', 'matching_report', 'anomaly_report', 'audit_trail', 'custom') NOT NULL,
    file_format ENUM('csv', 'excel', 'pdf', 'json', 'xml') NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500),
    file_size_kb INT,
    period_start DATE,
    period_end DATE,
    filters_json JSON,
    record_count INT,
    total_amount DECIMAL(15, 2),
    status ENUM('pending', 'processing', 'completed', 'failed') NOT NULL,
    error_message TEXT,
    exported_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    completed_at TIMESTAMP NULL,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (exported_by_user_id) REFERENCES users(id)
);

CREATE TABLE vat_reports (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    export_id BIGINT,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    report_type ENUM('monthly', 'quarterly', 'annual') NOT NULL,
    vat_rate DECIMAL(5, 2) NOT NULL,
    taxable_amount DECIMAL(15, 2) NOT NULL,
    vat_amount DECIMAL(15, 2) NOT NULL,
    category VARCHAR(100),
    transaction_count INT,
    generated_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (export_id) REFERENCES exports(id),
    FOREIGN KEY (generated_by_user_id) REFERENCES users(id)
);

CREATE TABLE settings (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT,
    company_id BIGINT,
    setting_category ENUM('general', 'ai', 'notifications', 'security', 'integration', 'export') NOT NULL,
    setting_key VARCHAR(100) NOT NULL,
    setting_value TEXT,
    setting_type ENUM('string', 'number', 'boolean', 'json') NOT NULL,
    is_encrypted BOOLEAN,
    description TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (company_id) REFERENCES companies(id)
);

CREATE TABLE ai_configurations (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    provider ENUM('openai', 'anthropic', 'custom', 'none') NOT NULL,
    api_key_encrypted TEXT,
    model_name VARCHAR(100),
    enable_invoice_extraction BOOLEAN,
    enable_auto_matching BOOLEAN,
    enable_anomaly_detection BOOLEAN,
    enable_category_suggestion BOOLEAN,
    auto_match_confidence_threshold DECIMAL(5, 4),
    auto_verify_confidence_threshold DECIMAL(5, 4),
    max_suggestions_per_item INT,
    learning_enabled BOOLEAN,
    updated_by_user_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (updated_by_user_id) REFERENCES users(id)
);

CREATE TABLE audit_logs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT,
    company_id BIGINT,
    action_type ENUM('create', 'read', 'update', 'delete', 'login', 'logout', 'permission_change', 'upload', 'import', 'export', 'match', 'unmatch', 'verify', 'resolve_anomaly', 'system') NOT NULL,
    entity_type VARCHAR(50),
    entity_id BIGINT,
    action_description TEXT,
    old_values JSON,
    new_values JSON,
    ip_address VARCHAR(45),
    user_agent TEXT,
    session_id VARCHAR(100),
    created_at TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (company_id) REFERENCES companies(id)
);

CREATE TABLE system_logs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    log_level ENUM('debug', 'info', 'warning', 'error', 'critical') NOT NULL,
    category VARCHAR(50),
    message TEXT NOT NULL,
    company_id BIGINT,
    user_id BIGINT,
    related_entity_type VARCHAR(50),
    related_entity_id BIGINT,
    stack_trace TEXT,
    error_code VARCHAR(50),
    metadata JSON,
    created_at TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_sessions (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    session_token VARCHAR(255) UNIQUE NOT NULL,
    ip_address VARCHAR(45),
    user_agent TEXT,
    device_type VARCHAR(50),
    browser VARCHAR(50),
    created_at TIMESTAMP,
    last_activity_at TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    logged_out_at TIMESTAMP NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE notifications (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    company_id BIGINT,
    notification_type ENUM('anomaly_detected', 'processing_complete', 'match_suggestion', 'access_granted', 'access_revoked', 'export_ready', 'system_alert', 'reminder') NOT NULL,
    priority ENUM('low', 'medium', 'high', 'urgent') NOT NULL,
    title VARCHAR(255) NOT NULL,
    message TEXT,
    related_entity_type VARCHAR(50),
    related_entity_id BIGINT,
    action_url VARCHAR(500),
    is_read BOOLEAN,
    read_at TIMESTAMP NULL,
    is_dismissed BOOLEAN,
    dismissed_at TIMESTAMP NULL,
    sent_via_email BOOLEAN,
    email_sent_at TIMESTAMP NULL,
    created_at TIMESTAMP,
    expires_at TIMESTAMP NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (company_id) REFERENCES companies(id)
);

CREATE TABLE ai_feedback (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    feedback_type ENUM('invoice_extraction', 'transaction_match', 'category_suggestion', 'anomaly_detection') NOT NULL,
    invoice_id BIGINT,
    transaction_id BIGINT,
    match_id BIGINT,
    anomaly_id BIGINT,
    ai_prediction TEXT,
    ai_confidence DECIMAL(5, 4),
    user_correction TEXT,
    was_correct BOOLEAN NOT NULL,
    feedback_notes TEXT,
    created_at TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (invoice_id) REFERENCES invoices(id),
    FOREIGN KEY (transaction_id) REFERENCES transactions(id),
    FOREIGN KEY (match_id) REFERENCES invoice_transaction_matches(id),
    FOREIGN KEY (anomaly_id) REFERENCES anomalies(id)
);

CREATE TABLE categories (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    parent_category_id BIGINT,
    category_type ENUM('income', 'expense', 'asset', 'liability') NOT NULL,
    account_code VARCHAR(50),
    tax_deductible BOOLEAN,
    is_active BOOLEAN,
    is_system BOOLEAN,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (parent_category_id) REFERENCES categories(id)
);

CREATE TABLE file_uploads (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    uploaded_by_user_id BIGINT NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    stored_file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_type VARCHAR(50),
    file_size_kb INT,
    mime_type VARCHAR(100),
    upload_type ENUM('invoice', 'transaction', 'document', 'profile', 'other') NOT NULL,
    related_entity_type VARCHAR(50),
    related_entity_id BIGINT,
    status ENUM('uploading', 'uploaded', 'processing', 'completed', 'error') NOT NULL,
    created_at TIMESTAMP,
    FOREIGN KEY (company_id) REFERENCES companies(id),
    FOREIGN KEY (uploaded_by_user_id) REFERENCES users(id)
);
